version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
      nodejs: 12
    commands:
      - apt update
      - rbenv install 2.6.0
      - rbenv global 2.6.0
      - gem install bundler:1.10.6
      - apt install make
      - apt install -y gcc
      - chmod a+rwx Gemfile.lock
      - bundle config disable_platform_warnings true
      - bundle install
artifacts:
  files:
    - '**/*'
  name: hello-world-build